[build-system]
requires = ["setuptools>=64", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0"

[project]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
name = "nomad-distribution"
description = "nomad distribution template"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
  "nomad-lab[parsing, infrastructure]==1.4.3.post1",
  "setuptools",
]


[project.urls]
repository = "https://github.com/fairmat-nfdi/fairmat-internal-oasis"

[project.optional-dependencies]
plugins = [
  "nomad-parser-plugins-electronic>=1.0",
  "fairmat-onboarding @ git+https://github.com/FAIRmat-NFDI/fairmat_onboarding.git@29e0118e0f5b4ed88b1d33e9b003510c50f2c915",
  "fairmat-events-form @ git+https://github.com/FAIRmat-NFDI/fairmat-events-form.git@bc5d79440b95ca03437d363f01b20115b091b98b",
  "nomad-training-resources @ git+https://github.com/FAIRmat-NFDI/nomad-training-resources.git@edc75976eb2f75ed452c482a62a42c9637b45570",
  "fairmat-members @ git+https://github.com/FAIRmat-NFDI/fairmat-members.git@59d94c377425f72bf8500505a495e32b068ba890",
  "fairmat-project-outputs @ git+https://github.com/ahm531/fairmat-project-outputs.git@08f65d54243c409fc42062e9aed03fde42ea9fbc",
]
jupyter = ["jupyter-events"]
gpu-action = []
cpu-action = []

dev = ["nomad-lab[parsing, infrastructure, dev]==1.4.3.post1"]

[tool.uv]
extra-index-url = [
  "https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple",
]
prerelease = "if-necessary-or-explicit"
override-dependencies = [
  "fairmat-onboarding @ git+https://github.com/FAIRmat-NFDI/fairmat_onboarding.git@29e0118e0f5b4ed88b1d33e9b003510c50f2c915",
]

[tool.setuptools.packages.find]
exclude = ["gui*", "docs*", "config*"]
