# Nginx configuration for handling HTTP requests

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen        80;
    server_name   fairmat-oasis.physik.hu-berlin.de;
    proxy_set_header Host $host;

    # Allow certbot ACME challenge through
    location /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    include conf.d/nginx_base_conf;
}
