services:
  api_host: "141.20.184.181"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true
  require_authentication: true
  allowed_users:
    - siamak.nakhaie@physik.hu-berlin.de

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/fairmat-nfdi/fairmat-internal-oasis/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "http://141.20.184.181/api"
  maintainer_email: "siamak.nakhaie@physik.hu-berlin.de"

logstash:
  enabled: false

temporal:
  enabled: true

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
